# Generated by Django 5.2.1 on 2025-05-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='img',
            field=models.ImageField(default='', upload_to='blogapp/images'),
        ),
    ]
